New param Max
code-on-yii/yii2-at-least-validator pull request #12
Opened 2017-03-28 17:16 UTC by Maykonn

Max param will set the maximum quantity of chosen attributes must to be filled.
If you have 3 attributes but just 1 must to be filled then set `max=1`. Default value for max is 0(all attributes can be filled).

2017-03-28 17:28 UTC, Maykonn commented
Resolving #12

2017-04-27 18:59 UTC, Maykonn commented
Hello!

Someone can merge this pull request on master?

2017-06-25 04:55 UTC, slinstj commented
Sorry, I have been very busy studying other things last months... I will review your PR and merge if it is ok. Thank you so much for your contribuition.

2017-06-25 13:58 UTC, slinstj commented on AtLeastValidator.php
> +     * Defaults to 1.
A minor error here: Defaults to 0;

2017-06-25 14:00 UTC, slinstj commented on AtLeastValidator.php
> +            ($this->max > 0 and $chosen > $this->max)
please, change `and` to `&&`

2017-06-25 14:02 UTC, sdlins reviewed
Please, remove the composer.lock off the set and re-send the PR after the other minor things commented on the code. Thank you so much for your contribuition. A propósito, sou do PR tmb. T+

2017-06-25 14:02 UTC, slinstj commented on AtLeastValidator.php
> -            ($this->max > 0 and $chosen > $this->max)
thnx

2017-06-25 14:12 UTC, slinstj commented on AtLeastValidator.php
> +            if($this->max > 0) {
Could you remove the dot from the end of the L90 and make a more simple sintax, please?
Suggestion:
`$this->message .= $this->max > 0 ? ' and at most {max} attribute(s).' : '.';`
Or you could even think a better way to generate a better error message for cases when `$min=0` and `$max=2`, for example.

Thank you so much.

2017-06-25 14:14 UTC, slinstj commented
@Maykonn, thank you for your work. I will wait you fix the minor details appointed here and resend the PR.

2018-04-24 13:56 UTC, sdlins requested changes
Please, check the feedback before I can merge your changes. Thank you!

2018-04-24 14:39 UTC, Maykonn commented
@slinstj Done :smile:

2018-05-02 02:39 UTC, slinstj commented
It will be closed till it is ok. Thank you for your contribution!

2018-05-02 02:39 UTC, closed without merging

2018-05-10 19:13 UTC, Maykonn commented
@slinstj The pull-request was accepted?

2018-05-12 03:09 UTC, slinstj commented
@Maykonn, it was not accepted for now. Please, read the messages I attached into the code. Thank you.

2018-05-12 03:27 UTC, Maykonn commented
I don't understand. See https://github.com/slinstj/yii2-at-least-validator/pull/12/commits/b418475e99cd5ffbf35745e3020a2904523369f6

2018-05-14 04:11 UTC, sdlins commented
I have seen. Please, see my comments [*in your PR*](https://github.com/slinstj/yii2-at-least-validator/pull/12/files/b418475e99cd5ffbf35745e3020a2904523369f6). Thank you again dude!